feat: updated all dockerfiles to use base dependency image and re-configured circleci

diff --git a/therr-client-web/Dockerfile b/therr-client-web/Dockerfile
--- a/therr-client-web/Dockerfile
+++ b/therr-client-web/Dockerfile
@@ -1,78 +1,74 @@
-ARG NODE_VERSION=20.18.1
-FROM node:$NODE_VERSION
-
-# Build in development allow devDependencies/dependencies to be installed correctly
-ENV NODE_ENV development
+# Rebuild the source code only when needed
+FROM therrapp/service-dependencies AS builder
 
 ARG BUILD_MODE=production
 ENV BUILD_MODE $BUILD_MODE
 
 RUN npm i npm@latest -g
 
+WORKDIR /app
+
 # Create app directory
-RUN mkdir /usr/src/app && mkdir /usr/src/app/client-web && chown -R node:node /usr/src/app
-WORKDIR /usr/src/app
+RUN mkdir /app/therr-client-web
+RUN mkdir /app/therr-client-web-dashboard
+WORKDIR /app/therr-client-web
+COPY . .
+COPY ../_bin/start-frontend-services.sh ./start-frontend-services.sh
 
-# the official node image provides an unprivileged user as a security best practice
-# but we have to manually enable it. We put it here so npm installs dependencies as the same
-# user who runs the app. 
-# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
-USER node
+COPY ../therr-client-web-dashboard ../therr-client-web-dashboard
 
-# Copy parent app config
-# A wildcard is used to ensure both package.json AND package-lock.json are copied
-# Note: This is the root mono-repo directory
-COPY ./package*.json ./
-COPY ./.babelrc ./
-COPY ./global-config.js ./
-COPY ./webpack.parts.js ./
-COPY ./node_modules ./node_modules
-COPY ./therr-public-library ./therr-public-library
-
-# Set libary directory permissions
-USER root
-RUN chown -R node:node /usr/src/app
-USER node
-
-# Install (shared) parent app dependencies and set PATH variable
-# Even in production, install devDependencies
-# RUN npm ci --no-optional
-ENV PATH $PATH:/usr/src/app/node_modules/.bin:$PATH
-
-# Install and build libraries (commented out bc run by ci/cd at base)
-# WORKDIR /usr/src/app/therr-public-library/therr-styles
-# RUN npm run build
-# WORKDIR /usr/src/app/therr-public-library/therr-js-utilities
-# RUN npm run build
-# WORKDIR /usr/src/app/therr-public-library/therr-react
-# RUN npm run build
-
-# Copy main app files
-WORKDIR /usr/src/app
-COPY ./therr-client-web ./therr-client-web
-COPY ./_bin/start-frontend-services.sh ./therr-client-web/start-frontend-services.sh
-COPY ./therr-client-web-dashboard ./therr-client-web-dashboard
-USER root
-RUN chown -R node:node /usr/src/app/therr-client-web /usr/src/app/therr-client-web-dashboard
-USER node
-
-WORKDIR /usr/src/app/therr-client-web-dashboard
+# Install microservice dependencies (client-web)
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci --ignore-scripts --omit=optional --legacy-peer-deps; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 RUN if [ "$BUILD_MODE" = "development" ]; then \
-      echo "Building dashboard app in $BUILD_MODE mode" \
-      && npm run build:dev; \
-    else \
-      echo "Building dashboard app in $BUILD_MODE mode" \
-      && npm run build; \
-    fi
+    echo "Building in $BUILD_MODE mode" \
+    && npm run build:dev; \
+  else \
+    echo "Building in $BUILD_MODE mode" \
+    && npm run build;\
+  fi
 
-WORKDIR /usr/src/app/therr-client-web
+# Install microservice dependencies (client-web-dashboard)
+WORKDIR /app/therr-client-web-dashboard
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci --ignore-scripts --omit=optional --legacy-peer-deps; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 RUN if [ "$BUILD_MODE" = "development" ]; then \
-      echo "Building web app in $BUILD_MODE mode" \
-      && npm run build:dev; \
-    else \
-      echo "Building web app in $BUILD_MODE mode" \
-      && npm run build; \
-    fi
+    echo "Building in $BUILD_MODE mode" \
+    && npm run build:dev; \
+  else \
+    echo "Building in $BUILD_MODE mode" \
+    && npm run build;\
+  fi
+WORKDIR /app/therr-client-web
+
+# Production image, copy all the files and run next
+FROM builder AS runner
+WORKDIR /app
+
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nodeuser
+
+COPY --from=builder /app/node_modules ./node_modules
+COPY --from=builder /app/therr-client-web ./therr-client-web
+COPY --from=builder /app/therr-client-web-dashboard ./therr-client-web-dashboard
+
+COPY --from=builder --chown=nodeuser:nodejs /app/therr-client-web/build ./
+COPY --from=builder --chown=nodeuser:nodejs /app/therr-client-web/build ./build
+COPY --from=builder --chown=nodeuser:nodejs /app/therr-client-web-dashboard/build ./
+COPY --from=builder --chown=nodeuser:nodejs /app/therr-client-web-dashboard/build ./build
+
+WORKDIR /app/therr-client-web
 
 # check every 30s to ensure this service returns HTTP 200
 # HEALTHCHECK --interval=30s CMD node healthcheck.js
@@ -83,7 +79,10 @@ ENV BUILD_MODE $BUILD_MODE
 ENV NODE_ENV $BUILD_MODE
 RUN echo "Running app in $NODE_ENV"
 
+USER nodeuser
 EXPOSE 7070 7071
+ENV PORT 7770
+ENV PORT_DASHBOARD 7771
 
 # Run both servers simultaneously
 # https://stackoverflow.com/questions/46496743/what-is-the-proper-way-to-start-multiple-local-node-js-servers
